apiVersion: v1
kind: Namespace
metadata:
  name: store-front
  labels: 
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: store-back
  labels: 
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
  namespace: store-front
  labels:
    app: catalog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: '200m'
              memory: '500Mi'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-cart-app
  namespace: store-front
  labels:
    app: user-cart-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-cart-app
  template:
    metadata:
      labels:
        app: user-cart-app
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: '200m'
              memory: '1000Mi'
            limits:
              memory: '10000Mi'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-service
  namespace: store-back
  labels:
    app: checkout-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout-service
  template:
    metadata:
      labels:
        app: checkout-service
        isolate: "true"
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: '200m'
              memory: '500Mi'
            limits:
              memory: '500Mi'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-ui
  namespace: store-front
  labels:
    app: console-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console-ui
  template:
    metadata:
      labels:
        app: console-ui
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: '20m'
            memory: '500Mi'
          limits:
            memory: '500Mi'
